[package]
name = "tiny-http"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.9"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.3.2"