[package]
name = "axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.3.4"
tokio = { version = "1.0", features = ["full"] }

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.3.2"
